-- 0907 source grain: chemical_cb (chemical_id, locale) → (chemical_id, cb_number, locale)
-- 保守原位演进(用户拍板: 不接受折损方案B):
--   1) 加 surrogate PK + cb_number 列(可 NULL = legacy "无CB号"行, 合法保留)
--   2) cb_number 从 chemicals.cb_number 确定性恢复(同一 callback 链写入, 非猜测)
--   3) 唯一粒度: (chemical_id, cb_number, locale) — 仅对 cb_number 非空行;
--      legacy NULL 行保留 (chemical_id, locale) 防重复(partial unique)
--   4) 不加 UNIQUE(cb_number)/(cb_number,locale) 全局强约束 —
--      CB001→chemical100 与 CB001→chemical200 是待治理事实, 不是 DB 不可能
BEGIN;

-- 1. surrogate PK (旧 PK (chemical_id,locale) 先删除, 再立新)
ALTER TABLE chemistry.chemical_cb
    ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE chemistry.chemical_cb DROP CONSTRAINT chemical_cb_pkey;
ALTER TABLE chemistry.chemical_cb
    ADD CONSTRAINT chemical_cb_pkey PRIMARY KEY (id);

-- 2. cb_number 列
ALTER TABLE chemistry.chemical_cb
    ADD COLUMN IF NOT EXISTS cb_number text;

-- 3. 确定性恢复: chemicals.cb_number 与 chemical_cb 同一 callback 事务写入
--    (upsert_externals 先写 cb 行再 coalesce 主表) → 同 chemical 的 zh-CN
--    行/语言行 cb 号即主表号。主表无号 = 该行抓取时 CB 无号 → 保留 NULL。
UPDATE chemistry.chemical_cb x
SET cb_number = c.cb_number, updated_at = now()
FROM chemistry.chemicals c
WHERE c.id = x.chemical_id AND c.cb_number IS NOT NULL AND x.cb_number IS NULL;

-- 4. 新唯一粒度
CREATE UNIQUE INDEX chemical_cb_source_grain_uidx
    ON chemistry.chemical_cb (chemical_id, cb_number, locale)
    WHERE cb_number IS NOT NULL;
-- legacy NULL grain 防重复(同旧行为)
CREATE UNIQUE INDEX chemical_cb_legacy_null_uidx
    ON chemistry.chemical_cb (chemical_id, locale)
    WHERE cb_number IS NULL;

COMMIT;
