#!/usr/bin/env python3
"""Space-conscious, resumable PubChem CID-SMILES rebuild.

The source SMILES and RDKit canonical SMILES are written in the same COPY.
CSV COPY is intentional: PostgreSQL text COPY interprets backslash+digits as
octal escapes and corrupts valid SMILES such as ``\\2``.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import io
import multiprocessing as mp
import os
import sys
import time
from pathlib import Path

import psycopg2
from rdkit import Chem, RDLogger, rdBase


SOURCE = Path("/var/www/ord-samelabs/CID-SMILES.gz")
EXPECTED_ROWS = 124_001_345
EXPECTED_SHA256 = "c1b26405f253160ac1e06d93989fd2e4800bb6ae353d38119eb59b2de1d1189f"
DB_DSN = os.environ.get(
    "PUBCHEM_DATABASE_URL",
    "dbname=huagongshe user=huagongshe host=127.0.0.1",
)
BATCH_ROWS = 100_000
WORKERS = 2
COPY_SQL = """
COPY pubchem.chemicals (pubchem_cid, pubchem_smiles, smiles)
FROM STDIN WITH (FORMAT csv, DELIMITER E'\\t', QUOTE E'\"', ESCAPE E'\"')
"""


def _worker_init() -> None:
    RDLogger.DisableLog("rdApp.*")


def _normalize(item: tuple[int, str]) -> tuple[int, str, str | None]:
    cid, raw = item
    try:
        mol = Chem.MolFromSmiles(raw)
        canonical = (
            Chem.MolToSmiles(mol, canonical=True, isomericSmiles=True)
            if mol is not None
            else None
        )
    except Exception:
        canonical = None
    return cid, raw, canonical


def _iter_source(after_cid: int = 0):
    with gzip.open(SOURCE, "rt", encoding="utf-8", newline="") as src:
        previous = 0
        for line_number, line in enumerate(src, 1):
            line = line.rstrip("\n")
            try:
                cid_text, raw = line.split("\t", 1)
                cid = int(cid_text)
            except Exception as exc:
                raise ValueError(f"Malformed source line {line_number}") from exc
            if not raw:
                raise ValueError(f"Empty SMILES at source line {line_number}")
            if cid <= previous:
                raise ValueError(
                    f"CID order violation at source line {line_number}: {cid} <= {previous}"
                )
            previous = cid
            if cid > after_cid:
                yield cid, raw


def _encode_batch(rows: list[tuple[int, str, str | None]]) -> io.StringIO:
    buf = io.StringIO()
    writer = csv.writer(
        buf,
        delimiter="\t",
        quotechar='"',
        doublequote=True,
        lineterminator="\n",
    )
    writer.writerows(rows)
    buf.seek(0)
    return buf


def connect():
    conn = psycopg2.connect(DB_DSN)
    conn.autocommit = False
    with conn.cursor() as cur:
        cur.execute("SET statement_timeout = 0")
        cur.execute("SET lock_timeout = '30s'")
        cur.execute("SET synchronous_commit = off")
    conn.commit()
    return conn


def self_test() -> None:
    test_rows = [
        (1, r"C/C=C\2/C(=O)N(C(=S)S2)C"),
        (2, r"C[C@H](O)C(=O)O"),
        (3, "not-a-smiles"),
    ]
    normalized = [_normalize(row) for row in test_rows]
    assert normalized[0][2] is not None
    assert normalized[1][2] is not None
    assert normalized[2][2] is None

    conn = connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "CREATE TEMP TABLE copy_escape_test "
                "(pubchem_cid integer, pubchem_smiles text, smiles text)"
            )
            buf = _encode_batch(normalized)
            cur.copy_expert(
                COPY_SQL.replace("pubchem.chemicals", "copy_escape_test"), buf
            )
            cur.execute(
                "SELECT pubchem_smiles, smiles "
                "FROM copy_escape_test ORDER BY pubchem_cid"
            )
            copied = cur.fetchall()
        conn.rollback()
    finally:
        conn.close()

    assert copied[0][0] == test_rows[0][1]
    assert "\x02" not in copied[0][0]
    assert copied[2][1] is None
    print(
        f"self-test passed: CSV preserves backslashes; RDKit={rdBase.rdkitVersion}",
        flush=True,
    )


def rebuild_schema() -> None:
    conn = connect()
    try:
        with conn.cursor() as cur:
            cur.execute("DROP TABLE IF EXISTS pubchem.chemicals")
            cur.execute("DROP TABLE IF EXISTS pubchem.chemicals_import_meta")
            cur.execute(
                """
                CREATE TABLE pubchem.chemicals (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pubchem_cid integer,
                    pubchem_smiles text,
                    smiles text,
                    preferred_name text,
                    synonyms jsonb,
                    created_at timestamptz,
                    updated_at timestamptz,
                    cas_numbers text[],
                    nikkaji_numbers text[],
                    chembl_ids text[],
                    ec_numbers text[],
                    unii_codes text[],
                    chebi_ids text[],
                    dtxsid text,
                    iupac_name text,
                    molecular_formula text,
                    average_mass double precision,
                    monoisotopic_mass double precision,
                    inchikey text,
                    mol public.mol,
                    morgan_bfp public.bfp,
                    morgan_sfp public.sfp
                ) WITH (fillfactor = 100)
                """
            )
            cur.execute(
                """
                COMMENT ON COLUMN pubchem.chemicals.id IS
                    'Autonomous chemical identity; independent of source namespaces';
                COMMENT ON COLUMN pubchem.chemicals.pubchem_cid IS
                    'Nullable PubChem source identifier; not a domain identity';
                COMMENT ON COLUMN pubchem.chemicals.pubchem_smiles IS
                    'Raw PubChem source SMILES; nullable for non-PubChem chemicals';
                COMMENT ON COLUMN pubchem.chemicals.smiles IS
                    'Canonical RDKit structure expression owned by chemicals';
                COMMENT ON COLUMN pubchem.chemicals.mol IS
                    'Derived RDKit Cartridge Mol; rebuildable from chemicals.smiles';
                COMMENT ON COLUMN pubchem.chemicals.morgan_bfp IS
                    'Derived Morgan bit fingerprint for similarity search';
                COMMENT ON COLUMN pubchem.chemicals.morgan_sfp IS
                    'Derived Morgan sparse fingerprint for similarity search'
                """
            )
            cur.execute(
                """
                CREATE TABLE pubchem.chemicals_import_meta (
                    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
                    source_path text NOT NULL,
                    source_sha256 text NOT NULL,
                    expected_rows bigint NOT NULL,
                    loaded_rows bigint NOT NULL DEFAULT 0,
                    canonicalized_rows bigint NOT NULL DEFAULT 0,
                    failed_rows bigint NOT NULL DEFAULT 0,
                    last_cid integer NOT NULL DEFAULT 0,
                    rdkit_version text NOT NULL,
                    status text NOT NULL,
                    started_at timestamptz NOT NULL DEFAULT now(),
                    updated_at timestamptz NOT NULL DEFAULT now(),
                    completed_at timestamptz
                )
                """
            )
            cur.execute(
                """
                INSERT INTO pubchem.chemicals_import_meta
                    (source_path, source_sha256, expected_rows, rdkit_version, status)
                VALUES (%s, %s, %s, %s, 'loading')
                """,
                (str(SOURCE), EXPECTED_SHA256, EXPECTED_ROWS, rdBase.rdkitVersion),
            )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
    print("schema rebuilt; old pubchem.chemicals removed", flush=True)


def load() -> None:
    conn = connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT loaded_rows, canonicalized_rows, failed_rows, last_cid, status
                FROM pubchem.chemicals_import_meta WHERE singleton
                """
            )
            state = cur.fetchone()
        if state is None:
            raise RuntimeError("Missing chemicals_import_meta; run --rebuild first")
        loaded, canonicalized, failed, last_cid, status = state
        if status == "complete":
            print("import already complete", flush=True)
            return

        started = time.monotonic()
        session_start_loaded = loaded
        pending: list[tuple[int, str, str | None]] = []
        ctx = mp.get_context("fork")
        with ctx.Pool(WORKERS, initializer=_worker_init) as pool:
            results = pool.imap(
                _normalize, _iter_source(after_cid=last_cid), chunksize=1_000
            )
            for row in results:
                pending.append(row)
                if len(pending) < BATCH_ROWS:
                    continue
                loaded, canonicalized, failed, last_cid = _commit_batch(
                    conn, pending, loaded, canonicalized, failed
                )
                pending.clear()
                _report(
                    started,
                    session_start_loaded,
                    loaded,
                    canonicalized,
                    failed,
                    last_cid,
                )

            if pending:
                loaded, canonicalized, failed, last_cid = _commit_batch(
                    conn, pending, loaded, canonicalized, failed
                )
                _report(
                    started,
                    session_start_loaded,
                    loaded,
                    canonicalized,
                    failed,
                    last_cid,
                )

        if loaded != EXPECTED_ROWS:
            raise RuntimeError(
                f"Loaded row mismatch: expected {EXPECTED_ROWS}, got {loaded}"
            )
        with conn.cursor() as cur:
            # Defer this index until after COPY: it is a source-key lookup and
            # integrity boundary, never the chemicals identity.
            cur.execute(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS chemicals_pubchem_cid_uidx
                ON pubchem.chemicals(pubchem_cid)
                WHERE pubchem_cid IS NOT NULL
                """
            )
            cur.execute("ANALYZE pubchem.chemicals")
            cur.execute(
                """
                UPDATE pubchem.chemicals_import_meta
                SET status='complete', completed_at=now(), updated_at=now()
                WHERE singleton
                """
            )
        conn.commit()
        print(
            f"COMPLETE rows={loaded:,} canonicalized={canonicalized:,} "
            f"failed={failed:,} elapsed={time.monotonic()-started:.1f}s",
            flush=True,
        )
    except Exception:
        conn.rollback()
        try:
            with conn.cursor() as cur:
                cur.execute(
                    "UPDATE pubchem.chemicals_import_meta "
                    "SET status='interrupted', updated_at=now() WHERE singleton"
                )
            conn.commit()
        except Exception:
            conn.rollback()
        raise
    finally:
        conn.close()


def _commit_batch(conn, rows, loaded, canonicalized, failed):
    batch_ok = sum(row[2] is not None for row in rows)
    batch_failed = len(rows) - batch_ok
    batch_last_cid = rows[-1][0]
    try:
        with conn.cursor() as cur:
            cur.copy_expert(COPY_SQL, _encode_batch(rows))
            cur.execute(
                """
                UPDATE pubchem.chemicals_import_meta
                SET loaded_rows = loaded_rows + %s,
                    canonicalized_rows = canonicalized_rows + %s,
                    failed_rows = failed_rows + %s,
                    last_cid = %s,
                    status = 'loading',
                    updated_at = now()
                WHERE singleton
                """,
                (len(rows), batch_ok, batch_failed, batch_last_cid),
            )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    return (
        loaded + len(rows),
        canonicalized + batch_ok,
        failed + batch_failed,
        batch_last_cid,
    )


def _report(started, session_start_loaded, loaded, canonicalized, failed, last_cid):
    elapsed = max(time.monotonic() - started, 0.001)
    rate = (loaded - session_start_loaded) / elapsed
    eta = (EXPECTED_ROWS - loaded) / rate if rate else 0
    print(
        f"rows={loaded:,}/{EXPECTED_ROWS:,} ok={canonicalized:,} "
        f"failed={failed:,} cid={last_cid:,} rate={rate:,.0f}/s "
        f"eta={eta/3600:.2f}h",
        flush=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=("self-test", "rebuild", "load", "all"))
    args = parser.parse_args()
    if args.action == "self-test":
        self_test()
    elif args.action == "rebuild":
        rebuild_schema()
    elif args.action == "load":
        load()
    else:
        self_test()
        rebuild_schema()
        load()


if __name__ == "__main__":
    main()
