#!/usr/bin/env python3
"""Migrate ORD reaction search relations onto autonomous reactions/chemicals.

Run on the database host as PostgreSQL's OS user:

    sudo -u postgres venv/bin/python migrate_ord_reactions.py

The migration is intentionally restartable and ordered around a 5 GiB disk
floor.  Large data is built beside the old objects, verified, then exposed
through compatibility views before the legacy physical tables are removed.
"""

from __future__ import annotations

import logging
import shutil
import sys
import time
from dataclasses import dataclass

import psycopg2
from psycopg2.extensions import connection as Connection


DB_NAME = "huagongshe"
DISK_PATH = "/"
MIN_FREE_BYTES = 5 * 1024**3
BATCH_SIZE = 25_000
LOCK_KEY = 7_219_240_719

EXPECTED_ORD_REACTIONS = 2_428_291
EXPECTED_MOL_REACTION_ROWS = 14_149_027
EXPECTED_RELATIONSHIPS = 13_023_629

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stdout,
)
log = logging.getLogger("migrate_ord_reactions")


@dataclass(frozen=True)
class Disk:
    free: int

    @property
    def gib(self) -> float:
        return self.free / 1024**3


def disk() -> Disk:
    return Disk(shutil.disk_usage(DISK_PATH).free)


def require_disk(phase: str) -> None:
    state = disk()
    log.info("disk before %s: %.2f GiB free", phase, state.gib)
    if state.free < MIN_FREE_BYTES:
        raise RuntimeError(
            f"disk guard stopped {phase}: {state.gib:.2f} GiB free, "
            "below the 5 GiB floor"
        )


def scalar(conn: Connection, sql: str, params: tuple = ()):
    with conn.cursor() as cur:
        cur.execute(sql, params)
        return cur.fetchone()[0]


def execute(conn: Connection, sql: str, params: tuple = ()) -> None:
    with conn.cursor() as cur:
        cur.execute(sql, params)


def set_meta(conn: Connection, key: str, value: str) -> None:
    execute(
        conn,
        """
        INSERT INTO public.reactions_migration_meta(key, value, updated_at)
        VALUES (%s, %s, now())
        ON CONFLICT (key) DO UPDATE
          SET value=excluded.value, updated_at=excluded.updated_at
        """,
        (key, value),
    )


def get_meta(conn: Connection, key: str, default: str = "") -> str:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT value FROM public.reactions_migration_meta WHERE key=%s", (key,)
        )
        row = cur.fetchone()
        return row[0] if row else default


def relation_kind(conn: Connection, qualified_name: str) -> str | None:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT relkind FROM pg_class WHERE oid=to_regclass(%s)",
            (qualified_name,),
        )
        row = cur.fetchone()
        return row[0] if row else None


def bootstrap(conn: Connection) -> None:
    execute(
        conn,
        """
        CREATE TABLE IF NOT EXISTS public.reactions_migration_meta (
            key text PRIMARY KEY,
            value text NOT NULL,
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """,
    )
    conn.commit()

    locked = scalar(conn, "SELECT pg_try_advisory_lock(%s)", (LOCK_KEY,))
    if not locked:
        raise RuntimeError("another reaction migration process holds the advisory lock")

    execute(conn, "SET statement_timeout='0'")
    execute(conn, "SET lock_timeout='10s'")
    execute(conn, "SET idle_in_transaction_session_timeout='10min'")
    execute(conn, "SET work_mem='64MB'")
    execute(conn, "SET maintenance_work_mem='256MB'")
    execute(conn, "SET max_parallel_workers_per_gather=2")

    if scalar(conn, "SELECT count(*) FROM ord.reaction") != EXPECTED_ORD_REACTIONS:
        raise RuntimeError("ord.reaction count changed; refusing a stale migration")
    if relation_kind(conn, "ord.mol_reaction") == "r":
        count = scalar(conn, "SELECT count(*) FROM ord.mol_reaction")
    else:
        count = scalar(conn, "SELECT COALESCE(sum(occurrence_count),0) FROM public.reaction_chemicals")
    if count != EXPECTED_MOL_REACTION_ROWS:
        raise RuntimeError(f"mol-reaction fact count changed: {count}")
    require_disk("bootstrap")


def create_roots(conn: Connection) -> None:
    if get_meta(conn, "roots") == "complete":
        log.info("roots already complete")
        return
    require_disk("reaction roots")
    if relation_kind(conn, "public.reactions") is not None:
        raise RuntimeError("public.reactions exists without a completed migration marker")
    if relation_kind(conn, "ord.legacy_reaction_map") is not None:
        raise RuntimeError("ord.legacy_reaction_map exists without a completed marker")

    log.info("creating autonomous reactions and ORD identity bridge")
    execute(
        conn,
        """
        CREATE TABLE public.reactions (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reaction_smiles text,
            reaction public.reaction,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """,
    )
    execute(
        conn,
        """
        CREATE TABLE ord.legacy_reaction_map (
            ord_reaction_id integer NOT NULL,
            reaction_id bigint NOT NULL
        )
        """,
    )
    execute(
        conn,
        """
        INSERT INTO ord.legacy_reaction_map(ord_reaction_id, reaction_id)
        SELECT id, nextval(pg_get_serial_sequence('public.reactions','id'))
        FROM ord.reaction
        ORDER BY id
        """,
    )
    execute(
        conn,
        "INSERT INTO public.reactions(id) SELECT reaction_id FROM ord.legacy_reaction_map ORDER BY reaction_id",
    )
    execute(
        conn,
        "ALTER TABLE ord.legacy_reaction_map ADD CONSTRAINT legacy_reaction_map_pkey PRIMARY KEY(ord_reaction_id)",
    )
    execute(
        conn,
        "ALTER TABLE ord.legacy_reaction_map ADD CONSTRAINT legacy_reaction_map_reaction_id_key UNIQUE(reaction_id)",
    )
    execute(
        conn,
        """
        ALTER TABLE ord.legacy_reaction_map
          ADD CONSTRAINT legacy_reaction_map_ord_fkey
          FOREIGN KEY(ord_reaction_id) REFERENCES ord.reaction(id) ON DELETE RESTRICT,
          ADD CONSTRAINT legacy_reaction_map_reaction_fkey
          FOREIGN KEY(reaction_id) REFERENCES public.reactions(id) ON DELETE RESTRICT
        """,
    )
    roots = scalar(conn, "SELECT count(*) FROM public.reactions")
    mapped = scalar(conn, "SELECT count(*) FROM ord.legacy_reaction_map")
    if roots != EXPECTED_ORD_REACTIONS or mapped != EXPECTED_ORD_REACTIONS:
        raise RuntimeError(f"reaction root mismatch: roots={roots}, map={mapped}")
    set_meta(conn, "roots", "complete")
    conn.commit()
    log.info("reaction roots complete: %d", roots)


def create_relationships(conn: Connection) -> None:
    if get_meta(conn, "relationships") == "complete":
        log.info("relationships already complete")
        return
    require_disk("reaction-chemical relationships")
    if relation_kind(conn, "public.reaction_chemicals") is not None:
        raise RuntimeError("public.reaction_chemicals exists without a completed marker")

    log.info("building deduplicated reaction-chemical roles")
    execute(
        conn,
        """
        CREATE TABLE public.reaction_chemicals (
            reaction_id bigint NOT NULL,
            chemical_id integer NOT NULL,
            role text NOT NULL,
            occurrence_count integer NOT NULL CHECK (occurrence_count > 0)
        )
        """,
    )
    execute(
        conn,
        """
        INSERT INTO public.reaction_chemicals
            (reaction_id, chemical_id, role, occurrence_count)
        SELECT rm.reaction_id,
               cm.chemical_id,
               grouped.role,
               grouped.occurrence_count
        FROM (
            SELECT mol_id,
                   reaction_id AS ord_reaction_id,
                   role,
                   count(*)::integer AS occurrence_count
            FROM ord.mol_reaction
            GROUP BY mol_id, reaction_id, role
        ) grouped
        JOIN ord.legacy_rdkit_mol_map cm
          ON cm.legacy_mol_id=grouped.mol_id
        JOIN ord.legacy_reaction_map rm
          ON rm.ord_reaction_id=grouped.ord_reaction_id
        """,
    )
    rows = scalar(conn, "SELECT count(*) FROM public.reaction_chemicals")
    facts = scalar(conn, "SELECT sum(occurrence_count) FROM public.reaction_chemicals")
    if rows != EXPECTED_RELATIONSHIPS or facts != EXPECTED_MOL_REACTION_ROWS:
        raise RuntimeError(f"relationship mismatch: rows={rows}, facts={facts}")
    conn.commit()

    require_disk("relationship indexes")
    execute(
        conn,
        """
        ALTER TABLE public.reaction_chemicals
          ADD CONSTRAINT reaction_chemicals_pkey
          PRIMARY KEY(reaction_id, chemical_id, role)
        """,
    )
    execute(
        conn,
        """
        CREATE INDEX reaction_chemicals_chemical_reaction_idx
          ON public.reaction_chemicals(chemical_id, reaction_id)
        """,
    )
    execute(
        conn,
        """
        ALTER TABLE public.reaction_chemicals
          ADD CONSTRAINT reaction_chemicals_reaction_fkey
          FOREIGN KEY(reaction_id) REFERENCES public.reactions(id)
          ON DELETE RESTRICT NOT VALID,
          ADD CONSTRAINT reaction_chemicals_chemical_fkey
          FOREIGN KEY(chemical_id) REFERENCES pubchem.chemicals(id)
          ON DELETE RESTRICT NOT VALID
        """,
    )
    conn.commit()

    log.info("validating relationship foreign keys")
    execute(
        conn,
        "ALTER TABLE public.reaction_chemicals VALIDATE CONSTRAINT reaction_chemicals_reaction_fkey",
    )
    conn.commit()
    execute(
        conn,
        "ALTER TABLE public.reaction_chemicals VALIDATE CONSTRAINT reaction_chemicals_chemical_fkey",
    )
    execute(conn, "ANALYZE public.reaction_chemicals")
    set_meta(conn, "relationships", "complete")
    conn.commit()
    log.info("relationships complete: %d rows preserving %d facts", rows, facts)


def verify_roles(conn: Connection) -> None:
    mismatches = scalar(
        conn,
        """
        SELECT count(*)
        FROM (
            (SELECT role, count(*)::bigint AS n
             FROM ord.mol_reaction GROUP BY role)
            EXCEPT
            (SELECT role, sum(occurrence_count)::bigint AS n
             FROM public.reaction_chemicals GROUP BY role)
        ) differences
        """,
    )
    if mismatches:
        raise RuntimeError(f"role aggregates differ in {mismatches} rows")


def cut_over_mol_reaction(conn: Connection) -> None:
    if get_meta(conn, "mol_reaction_cutover") == "complete":
        log.info("mol_reaction cutover already complete")
        return
    require_disk("mol_reaction cutover")
    verify_roles(conn)

    kind = relation_kind(conn, "ord.mol_reaction")
    if kind != "r":
        raise RuntimeError(f"expected physical ord.mol_reaction, found relkind={kind}")
    log.info("cutting ord.mol_reaction over to a compatibility view")
    execute(conn, "LOCK TABLE ord.mol_reaction IN ACCESS EXCLUSIVE MODE")
    execute(conn, "ALTER TABLE ord.mol_reaction RENAME TO mol_reaction_legacy")
    execute(
        conn,
        """
        CREATE VIEW ord.mol_reaction AS
        SELECT cm.legacy_mol_id AS mol_id,
               rm.ord_reaction_id AS reaction_id,
               rc.role
        FROM public.reaction_chemicals rc
        JOIN ord.legacy_rdkit_mol_map cm
          ON cm.chemical_id=rc.chemical_id
        JOIN ord.legacy_reaction_map rm
          ON rm.reaction_id=rc.reaction_id
        CROSS JOIN LATERAL generate_series(1, rc.occurrence_count) repeated(n)
        """,
    )

    view_count = scalar(conn, "SELECT count(*) FROM ord.mol_reaction")
    if view_count != EXPECTED_MOL_REACTION_ROWS:
        raise RuntimeError(f"compatibility view count mismatch: {view_count}")
    legacy_count = scalar(conn, "SELECT count(*) FROM ord.mol_reaction_legacy")
    if legacy_count != view_count:
        raise RuntimeError(
            f"legacy/view count mismatch: legacy={legacy_count}, view={view_count}"
        )
    verify_roles(conn)

    execute(conn, "DROP TABLE ord.mol_reaction_legacy")
    set_meta(conn, "mol_reaction_cutover", "complete")
    conn.commit()
    execute(conn, "CHECKPOINT")
    log.info("legacy mol_reaction removed; disk now %.2f GiB free", disk().gib)


def populate_reaction_payload(conn: Connection) -> None:
    if get_meta(conn, "reaction_payload") == "complete":
        log.info("reaction payload already complete")
        return
    last = int(get_meta(conn, "reaction_payload_last_ord_id", "0") or "0")
    max_id = scalar(conn, "SELECT max(id) FROM ord.reaction")
    log.info("absorbing reaction payload in %d-row source-ID batches", BATCH_SIZE)

    while last < max_id:
        require_disk(f"reaction payload after ord id {last}")
        high = min(last + BATCH_SIZE, max_id)
        started = time.monotonic()
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE public.reactions target
                SET reaction_smiles=source.reaction_smiles,
                    reaction=legacy.reaction,
                    updated_at=now()
                FROM ord.legacy_reaction_map mapping
                JOIN ord.reaction source
                  ON source.id=mapping.ord_reaction_id
                LEFT JOIN rdkit.reactions legacy
                  ON legacy.id=source.rdkit_reaction_id
                WHERE target.id=mapping.reaction_id
                  AND mapping.ord_reaction_id > %s
                  AND mapping.ord_reaction_id <= %s
                  AND (
                    target.reaction_smiles IS DISTINCT FROM source.reaction_smiles
                    OR (legacy.reaction IS NOT NULL AND target.reaction IS NULL)
                  )
                """,
                (last, high),
            )
            changed = cur.rowcount
        set_meta(conn, "reaction_payload_last_ord_id", str(high))
        conn.commit()
        last = high
        if high % (BATCH_SIZE * 10) == 0 or high == max_id:
            log.info(
                "payload through ord id %d/%d; changed=%d; %.1fs; %.2f GiB free",
                high,
                max_id,
                changed,
                time.monotonic() - started,
                disk().gib,
            )

    mismatches = scalar(
        conn,
        """
        SELECT count(*)
        FROM ord.legacy_reaction_map mapping
        JOIN ord.reaction source ON source.id=mapping.ord_reaction_id
        JOIN public.reactions target ON target.id=mapping.reaction_id
        WHERE target.reaction_smiles IS DISTINCT FROM source.reaction_smiles
        """,
    )
    if mismatches:
        raise RuntimeError(f"reaction_smiles validation failed: {mismatches} mismatches")
    expected_rdkit = scalar(
        conn, "SELECT count(*) FROM ord.reaction WHERE rdkit_reaction_id IS NOT NULL"
    )
    copied_rdkit = scalar(
        conn, "SELECT count(*) FROM public.reactions WHERE reaction IS NOT NULL"
    )
    if copied_rdkit != expected_rdkit:
        raise RuntimeError(
            f"RDKit reaction payload mismatch: expected={expected_rdkit}, copied={copied_rdkit}"
        )
    execute(conn, "ANALYZE public.reactions")
    set_meta(conn, "reaction_payload", "complete")
    conn.commit()
    log.info("reaction payload complete; RDKit objects copied=%d", copied_rdkit)


def create_reaction_index(conn: Connection) -> None:
    if get_meta(conn, "reaction_index") == "complete":
        log.info("reaction index already complete")
        return
    require_disk("reaction GiST index")
    execute(
        conn,
        """
        CREATE INDEX IF NOT EXISTS reactions_reaction_gist_idx
          ON public.reactions USING gist(reaction)
          WHERE reaction IS NOT NULL
        """,
    )
    set_meta(conn, "reaction_index", "complete")
    conn.commit()


def decouple_legacy_rdkit_reactions(conn: Connection) -> None:
    if get_meta(conn, "rdkit_reactions_cutover") == "complete":
        log.info("rdkit.reactions cutover already complete")
        return
    if relation_kind(conn, "rdkit.reactions") != "r":
        raise RuntimeError("expected the legacy physical rdkit.reactions table")
    require_disk("rdkit.reactions cutover")

    execute(
        conn,
        """
        CREATE TABLE ord.legacy_rdkit_reaction_map AS
        SELECT source.rdkit_reaction_id AS legacy_rdkit_reaction_id,
               min(mapping.reaction_id) AS reaction_id
        FROM ord.reaction source
        JOIN ord.legacy_reaction_map mapping
          ON mapping.ord_reaction_id=source.id
        WHERE source.rdkit_reaction_id IS NOT NULL
        GROUP BY source.rdkit_reaction_id
        """,
    )
    execute(
        conn,
        """
        ALTER TABLE ord.legacy_rdkit_reaction_map
          ADD CONSTRAINT legacy_rdkit_reaction_map_pkey
          PRIMARY KEY(legacy_rdkit_reaction_id),
          ALTER COLUMN reaction_id SET NOT NULL,
          ADD CONSTRAINT legacy_rdkit_reaction_map_reaction_fkey
          FOREIGN KEY(reaction_id) REFERENCES public.reactions(id) ON DELETE RESTRICT
        """,
    )
    mapped = scalar(conn, "SELECT count(*) FROM ord.legacy_rdkit_reaction_map")
    legacy = scalar(conn, "SELECT count(*) FROM rdkit.reactions")
    if mapped != legacy:
        raise RuntimeError(f"legacy RDKit reaction map mismatch: {mapped} != {legacy}")

    execute(
        conn,
        "ALTER TABLE ord.reaction DROP CONSTRAINT reaction_rdkit_reaction_id_fkey",
    )
    execute(
        conn,
        """
        ALTER TABLE ord.reaction
          ADD CONSTRAINT reaction_rdkit_reaction_id_fkey
          FOREIGN KEY(rdkit_reaction_id)
          REFERENCES ord.legacy_rdkit_reaction_map(legacy_rdkit_reaction_id)
          ON DELETE RESTRICT NOT VALID
        """,
    )
    execute(
        conn,
        "ALTER TABLE ord.reaction VALIDATE CONSTRAINT reaction_rdkit_reaction_id_fkey",
    )
    execute(conn, "ALTER TABLE rdkit.reactions RENAME TO reactions_legacy")
    execute(
        conn,
        """
        CREATE VIEW rdkit.reactions AS
        SELECT mapping.legacy_rdkit_reaction_id AS id,
               target.reaction_smiles,
               target.reaction
        FROM ord.legacy_rdkit_reaction_map mapping
        JOIN public.reactions target ON target.id=mapping.reaction_id
        WHERE target.reaction IS NOT NULL
        """,
    )

    view_rows = scalar(conn, "SELECT count(*) FROM rdkit.reactions")
    if view_rows != legacy:
        raise RuntimeError(f"rdkit.reactions compatibility view mismatch: {view_rows}")
    smiles_mismatches = scalar(
        conn,
        """
        SELECT count(*)
        FROM rdkit.reactions view_row
        JOIN rdkit.reactions_legacy legacy_row USING (id)
        WHERE view_row.reaction_smiles IS DISTINCT FROM legacy_row.reaction_smiles
        """,
    )
    if smiles_mismatches:
        raise RuntimeError(
            f"rdkit.reactions SMILES compatibility mismatch: {smiles_mismatches}"
        )
    execute(conn, "DROP TABLE rdkit.reactions_legacy")
    set_meta(conn, "rdkit_reactions_cutover", "complete")
    conn.commit()
    execute(conn, "CHECKPOINT")
    log.info("legacy physical rdkit.reactions removed")


def final_report(conn: Connection) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
              (SELECT count(*) FROM public.reactions) AS reactions,
              (SELECT count(*) FROM public.reaction_chemicals) AS relationships,
              (SELECT sum(occurrence_count) FROM public.reaction_chemicals) AS facts,
              (SELECT count(*) FROM public.reactions WHERE reaction_smiles IS NOT NULL) AS with_smiles,
              (SELECT count(*) FROM public.reactions WHERE reaction IS NOT NULL) AS with_rdkit,
              (SELECT count(*) FROM ord.legacy_reaction_map) AS ord_map
            """
        )
        row = cur.fetchone()
    log.info(
        "FINAL reactions=%d relationships=%d facts=%d smiles=%d rdkit=%d ord_map=%d disk=%.2fGiB",
        *row,
        disk().gib,
    )


def main() -> int:
    conn = psycopg2.connect(dbname=DB_NAME, application_name="reaction_domain_migration")
    conn.autocommit = False
    try:
        bootstrap(conn)
        create_roots(conn)
        create_relationships(conn)
        cut_over_mol_reaction(conn)
        populate_reaction_payload(conn)
        create_reaction_index(conn)
        decouple_legacy_rdkit_reactions(conn)
        final_report(conn)
        return 0
    except Exception:
        conn.rollback()
        log.exception("migration stopped safely")
        return 1
    finally:
        try:
            execute(conn, "SELECT pg_advisory_unlock(%s)", (LOCK_KEY,))
            conn.commit()
        except Exception:
            pass
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
